### ISSUE TITLE
Need to add a check of the boolean value (isActive) everywhere

### ISSUE THREAD

**Issue by youssefalb** [youssefalb/HealthHub#37]
We need to verify the value of isActive in order to enable users to perform actions in the app.

**Comment by drago20013** [comment]
is it in all places or just disable the login possibility?

**Comment by youssefalb** [comment]
> is it in all places or just disable the login possibility?

I think in all places would be much more better

**Comment by AsserElfeki** [comment]
wdym ?

**Comment by youssefalb** [comment]
@AsserElfeki 
isActive shows whether the user is banned or no, so we should restrict/allow some functionalities based on isActive value all over the app

**Comment by drago20013** [comment]
its checked on sign in
